### PR TITLE
fixing issue #39

### PR DESCRIPTION
**Pull request by alexneo2003**
fixing issue #39 
support jest >= 27

### CODE REVIEW

**Comment by alexneo2003** [comment]
@mattphillips can you review PR

**Comment by adamchenwei** [comment]
oh man it will be so nice this can be in :D

**Comment by Shakes03** [comment]
+1

**Comment by golergka** [comment]
I'm also having the same issue, can this be merged please?

**Comment by GerkinDev** [comment]
For now, `jest-expect-message` breaks all my build/check pipelines. @alexneo2003 seen that the repo owner @mattphillips seems too busy to merge this right now (I totally get it, he got a life and a job), would it be possible for you to build the package & commit + push built artifacts on github out of this PR ? I won't ask for support, I just want my CI to stop yelling at me :sob: .

In the meantime, I've **temporarily** solved the problem this way:

```sh
npm i -D https://github.com/alexneo2003/jest-expect-message#issue-39
cd ./node_modules/jest-expect-message
npm i
npm run build
cd ../../
```
It is also possible to automate the build so that it is not removed after `npm install` by adding a script in `package.json`: 

```js
// ...
    "postinstall": "cd ./node_modules/jest-expect-message && npm i && npm run build && cd ../../",
// ...
```

:beers:  cheers

**Comment by alexneo2003** [comment]
@GerkinDev @golergka @Shakes03 @adamchenwei @beatrichartz @jkoenig134 @ambroselittle
i'm publishing package @alex_neo/jest-expect-message
check pls
connect to project as 
```javascript
  setupFilesAfterEnv: ['@alex_neo/jest-expect-message'],
```

**Comment by GerkinDev** [comment]
This is great, thank you.

Hope though that the original package owner will get some time to merge PRs

**Comment by ambroselittle** [comment]
@alexneo2003, confirmed works on mine. thank you.

**Comment by Trainmaster** [comment]
@mattphillips Is there any chance that this can get merged? Or how about moving it to https://github.com/orgs/jest-community so it doesn't rely on a single person?

**Comment by alexneo2003** [comment]
> @mattphillips Is there any chance that this can get merged? Or how about moving it to https://github.com/orgs/jest-community so it doesn't rely on a single person?

Check [this](https://github.com/mattphillips/jest-expect-message/pull/40#issuecomment-865654859)

**Comment by gracepark** [comment]
@mattphillips - I know this has been mentioned a few times here already, but would love if this could get merged in if you have a chance! Thank you, and thank you @alexneo2003 for the fix!

**Comment by DanKaplanSES** [comment]
I also would like this to be merged @mattphillips thanks

**Comment by DanKaplanSES** [comment]
@jongio I noticed you are the other contributors of this repository. Do you have the ability to merge this feature in? Thanks!

**Comment by jongio** [comment]
Sorry, I do not.

**Comment by wycats** [comment]
I hit this issue today and would also like it to be merged. @mattphillips do you need any help?

**Comment by jcollum** [comment]
@mattphillips  I suggest you add another maintainer. Jest 27 was released a good long while ago.

**Comment by orihomie** [comment]
How to skip such type of warnings?
> ts-jest[ts-compiler] (WARN) test/e2e/example.e2e.ts:110:19 - error TS2554: Expected 1 arguments, but got 2.

**Comment by rinogo** [comment]
What would you think about giving the Jest community a nice Christmas gift, @mattphillips ? 🎄🙏😁

**Comment by phawxby** [comment]
I think this highlights why this functionality should've been part of core from the beginning.

**Review by KosnIre — APPROVED** [review]

**Comment by KosnIre** [comment]
My 2 cents mean little here, but this is a good fix and retains backwards-compatibility. 

I will note for others that I found `jest-chain` has a [similar issue](https://github.com/mattphillips/jest-chain/issues/34#issuecomment-955062092) where one of the commenters suggests using the [patch-package](https://github.com/ds300/patch-package) project.

**Comment by slavafomin** [comment]
@mattphillips hello?

**Comment by jcollum** [comment]
@jongio do you have any ability to add maintainers? It's been almost 6 months since I pinged Matt Phillips about this and 9 months since this ticket was opened.

**Comment by jongio** [comment]
No sorry.

**Comment by thephilwells** [comment]
Please. There must be a way we can merge this.

**Comment by jongio** [comment]
https://twitter.com/jongallant/status/1516437398032244738

**Comment by HumbertoL** [comment]
Since this hasn't been fixed in a year, I've gone ahead and published a new version of the package: `jest-27-expect-message`.

I'll mark this package as deprecated if the official `jest-expect-message` is ever updated

https://www.npmjs.com/package/jest-27-expect-message

**Comment by mattphillips** [comment]
Sorry for the delay. Thanks for the fix @alexneo2003

**Comment by mattphillips** [comment]
Fix is available in: https://www.npmjs.com/package/jest-expect-message/v/1.0.4

**Pull request merged**
