### PR TITLE
Added type support for TypeScript

### PR DESCRIPTION
**Pull request by DonIsaac**
### What

Added type declarations to enhance TypeScript support

- The original `expect` signature is overwritten to reflect the new
  `expect` function
- Declarations are made available to consumers via the `types` property
  in `package.json`
- Updated the `withMessage` test file to reflect these changes.

### Why
#26 

### Notes
n/a
### Housekeeping

- [x] Unit tests
- [ ] Documentation is up to date 
  *No feature changes, so this shouldn't be necessary*
- [x] No additional lint warnings

### CODE REVIEW

**Comment by DonIsaac** [comment]
@mattphillips Is there anything I need to address in this pull request, or is it ready to merge?

**Comment by cefn** [comment]
Isn't this already available via https://www.npmjs.com/package/@types/jest-expect-message ?

By way of a working example from our source...

```typescript
import 'jest';
import 'jest-expect-message';
declare const expect: jest.Expect;
//...
expect(collection.deleteCollection(), `Could not delete collection ${emptyCollectionName}`).toBe(true);
```

**Comment by DonIsaac** [comment]
@cefn I'm not up-to-date on the status of this package. This PR was inspired by an issue (#26) I answered about a year ago.

**Comment by HADMARINE** [comment]
I think I resolved by adding types in tsconfig.json

```json
{
  "compilerOptions": {
    ...
        "types": ["@types/jest", "@types/jest-expect-message"],     
    ....
  }
```

and also disabling rules of eslint. (jest/valid-expect)

**Comment by DonIsaac** [comment]
@HADMARINE I believe that solution overrides the default type locations, meaning that packages in `@types` will no longer be included (unless explicitly specified).

**Comment by mattphillips** [comment]
Thanks for the PR @DonIsaac. As part of the various issues/PRs I've added types to this package and docs for configuring them [see here](https://github.com/mattphillips/jest-expect-message#configure-typescript). So I'll go ahead and close this for now.

**Pull request closed without merging**
